import type { NewEmployee } from '../schema/index.js';

/** Demo roster (seed-data/demo/employee_master.csv). City tier per policy 3.1. */
export const EMPLOYEE_SEED: NewEmployee[] = [
  // Deliberately separate from the business approval hierarchy. This account
  // is for organisation-level oversight and cannot approve or pay claims.
  {
    empCode: 'AC-ADMIN',
    name: 'Acme Administrator',
    email: 'admin@acmecorp.com',
    designation: 'System Administrator',
    department: 'Corporate',
    costCentre: 'CE001',
    city: 'Mumbai',
    cityTier: 'TIER_1',
    reportingManagerCode: null,
    role: 'Admin',
  },
  {
    empCode: 'AC-4471',
    name: 'Chaitanya Reddy',
    email: 'chaitanya.reddy@acmecorp.com',
    designation: 'Manager - Key Accounts',
    department: 'Sales',
    costCentre: 'CE110',
    city: 'Pune',
    cityTier: 'TIER_1',
    reportingManagerCode: 'AC-2210',
    role: 'Employee',
  },
  {
    empCode: 'AC-2210',
    name: 'Suresh Iyer',
    email: 'suresh.iyer@acmecorp.com',
    designation: 'Deputy General Manager',
    department: 'Sales',
    costCentre: 'CE110',
    city: 'Pune',
    cityTier: 'TIER_1',
    reportingManagerCode: 'AC-1108',
    role: 'Reporting Manager',
  },
  {
    empCode: 'AC-1108',
    name: 'Meera Krishnan',
    email: 'meera.krishnan@acmecorp.com',
    designation: 'Head of Department - Sales',
    department: 'Sales',
    costCentre: 'CE100',
    city: 'Mumbai',
    cityTier: 'TIER_1',
    reportingManagerCode: 'AC-1002',
    role: 'Head of Department',
  },
  {
    empCode: 'AC-1002',
    name: 'Arvind Rao',
    email: 'arvind.rao@acmecorp.com',
    designation: 'Head of Division - Commercial',
    department: 'Commercial',
    costCentre: 'CE001',
    city: 'Mumbai',
    cityTier: 'TIER_1',
    reportingManagerCode: 'AC-1000',
    role: 'Head of Division',
  },
  {
    empCode: 'AC-1000',
    name: 'Nandita Shah',
    email: 'nandita.shah@acmecorp.com',
    designation: 'Managing Director',
    department: 'Corporate',
    costCentre: 'CE001',
    city: 'Mumbai',
    cityTier: 'TIER_1',
    reportingManagerCode: null,
    role: 'MD',
  },
  {
    empCode: 'AC-3305',
    name: 'Ravi Menon',
    email: 'ravi.menon@acmecorp.com',
    designation: 'Manager - Finance Shared Services',
    department: 'Finance',
    costCentre: 'CE900',
    city: 'Pune',
    cityTier: 'TIER_1',
    reportingManagerCode: 'AC-3300',
    role: 'Finance',
  },
  {
    empCode: 'AC-3300',
    name: 'Kavitha Balan',
    email: 'kavitha.balan@acmecorp.com',
    designation: 'Controller',
    department: 'Finance',
    costCentre: 'CE900',
    city: 'Pune',
    cityTier: 'TIER_1',
    reportingManagerCode: 'AC-1002',
    role: 'Finance',
  },
  {
    empCode: 'AC-5182',
    name: 'Deepa Nair',
    email: 'deepa.nair@acmecorp.com',
    designation: 'Manager - Presales',
    department: 'Sales',
    costCentre: 'CE110',
    city: 'Chennai',
    cityTier: 'TIER_1',
    reportingManagerCode: 'AC-2210',
    role: 'Employee',
  },
  {
    empCode: 'AC-4490',
    name: 'Imran Qureshi',
    email: 'imran.qureshi@acmecorp.com',
    designation: 'Executive - Sales',
    department: 'Sales',
    costCentre: 'CE110',
    city: 'Pune',
    cityTier: 'TIER_1',
    reportingManagerCode: 'AC-2210',
    role: 'Employee',
  },
];
