import type { NewEmployee } from '../schema/index.js';

/** Verbatim from pack/employee_master.csv. City tier per policy 3.1. */
export const EMPLOYEE_SEED: NewEmployee[] = [
  // Deliberately separate from the business approval hierarchy. This account
  // is for organisation-level oversight and cannot approve or pay claims.
  {
    empCode: 'NX-ADMIN',
    name: 'Nortex Administrator',
    email: 'admin@nortexindustries.com',
    designation: 'System Administrator',
    department: 'Corporate',
    costCentre: 'CE001',
    city: 'Mumbai',
    cityTier: 'TIER_1',
    reportingManagerCode: null,
    role: 'Admin',
  },
  {
    empCode: 'NX-4471',
    name: 'Chaitanya Reddy',
    email: 'chaitanya.reddy@nortexindustries.com',
    designation: 'Manager - Key Accounts',
    department: 'Sales',
    costCentre: 'CE110',
    city: 'Pune',
    cityTier: 'TIER_1',
    reportingManagerCode: 'NX-2210',
    role: 'Employee',
  },
  {
    empCode: 'NX-2210',
    name: 'Suresh Iyer',
    email: 'suresh.iyer@nortexindustries.com',
    designation: 'Deputy General Manager',
    department: 'Sales',
    costCentre: 'CE110',
    city: 'Pune',
    cityTier: 'TIER_1',
    reportingManagerCode: 'NX-1108',
    role: 'Reporting Manager',
  },
  {
    empCode: 'NX-1108',
    name: 'Meera Krishnan',
    email: 'meera.krishnan@nortexindustries.com',
    designation: 'Head of Department - Sales',
    department: 'Sales',
    costCentre: 'CE100',
    city: 'Mumbai',
    cityTier: 'TIER_1',
    reportingManagerCode: 'NX-1002',
    role: 'Head of Department',
  },
  {
    empCode: 'NX-1002',
    name: 'Arvind Rao',
    email: 'arvind.rao@nortexindustries.com',
    designation: 'Head of Division - Commercial',
    department: 'Commercial',
    costCentre: 'CE001',
    city: 'Mumbai',
    cityTier: 'TIER_1',
    reportingManagerCode: 'NX-1000',
    role: 'Head of Division',
  },
  {
    empCode: 'NX-1000',
    name: 'Nandita Shah',
    email: 'nandita.shah@nortexindustries.com',
    designation: 'Managing Director',
    department: 'Corporate',
    costCentre: 'CE001',
    city: 'Mumbai',
    cityTier: 'TIER_1',
    reportingManagerCode: null,
    role: 'MD',
  },
  {
    empCode: 'NX-3305',
    name: 'Ravi Menon',
    email: 'ravi.menon@nortexindustries.com',
    designation: 'Manager - Finance Shared Services',
    department: 'Finance',
    costCentre: 'CE900',
    city: 'Pune',
    cityTier: 'TIER_1',
    reportingManagerCode: 'NX-3300',
    role: 'Finance',
  },
  {
    empCode: 'NX-3300',
    name: 'Kavitha Balan',
    email: 'kavitha.balan@nortexindustries.com',
    designation: 'Controller',
    department: 'Finance',
    costCentre: 'CE900',
    city: 'Pune',
    cityTier: 'TIER_1',
    reportingManagerCode: 'NX-1002',
    role: 'Finance',
  },
  {
    empCode: 'NX-5182',
    name: 'Deepa Nair',
    email: 'deepa.nair@nortexindustries.com',
    designation: 'Manager - Presales',
    department: 'Sales',
    costCentre: 'CE110',
    city: 'Chennai',
    cityTier: 'TIER_1',
    reportingManagerCode: 'NX-2210',
    role: 'Employee',
  },
  {
    empCode: 'NX-4490',
    name: 'Imran Qureshi',
    email: 'imran.qureshi@nortexindustries.com',
    designation: 'Executive - Sales',
    department: 'Sales',
    costCentre: 'CE110',
    city: 'Pune',
    cityTier: 'TIER_1',
    reportingManagerCode: 'NX-2210',
    role: 'Employee',
  },
];
