/**
 * Machine-readable error codes. The frontend switches on `error.code`,
 * never on the human `error.message` (which may change wording).
 *
 * Naming: DOMAIN_CONDITION, SCREAMING_SNAKE_CASE.
 */
export const ErrorCode = {
  // generic / transport
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  CONFLICT: 'CONFLICT',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // database
  DB_UNIQUE_VIOLATION: 'DB_UNIQUE_VIOLATION',
  DB_FOREIGN_KEY_VIOLATION: 'DB_FOREIGN_KEY_VIOLATION',
  DB_NOT_NULL_VIOLATION: 'DB_NOT_NULL_VIOLATION',
  DB_CHECK_VIOLATION: 'DB_CHECK_VIOLATION',

  // auth / identity
  USER_HEADER_MISSING: 'USER_HEADER_MISSING',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ROLE_NOT_PERMITTED: 'ROLE_NOT_PERMITTED',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_NOT_REGISTERED: 'ACCOUNT_NOT_REGISTERED',
  ACCOUNT_ALREADY_REGISTERED: 'ACCOUNT_ALREADY_REGISTERED',
  EMAIL_NOT_RECOGNISED: 'EMAIL_NOT_RECOGNISED',

  // domain: trips / claims
  TRIP_NOT_FOUND: 'TRIP_NOT_FOUND',
  CLAIM_LINE_NOT_FOUND: 'CLAIM_LINE_NOT_FOUND',
  CLAIM_NOT_EDITABLE: 'CLAIM_NOT_EDITABLE',
  CLAIM_ALREADY_SUBMITTED: 'CLAIM_ALREADY_SUBMITTED',
  CLAIM_MISSING_PROOF: 'CLAIM_MISSING_PROOF',
  CLAIM_HAS_UNRESOLVED_LINES: 'CLAIM_HAS_UNRESOLVED_LINES',
  SUBMISSION_WINDOW_EXPIRED: 'SUBMISSION_WINDOW_EXPIRED',

  // domain: approvals
  APPROVAL_STEP_NOT_FOUND: 'APPROVAL_STEP_NOT_FOUND',
  APPROVAL_OUT_OF_ORDER: 'APPROVAL_OUT_OF_ORDER',
  APPROVER_IS_CLAIMANT: 'APPROVER_IS_CLAIMANT',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',

  // domain: ingestion
  DOCUMENT_PARSE_FAILED: 'DOCUMENT_PARSE_FAILED',
  UNSUPPORTED_DOCUMENT_TYPE: 'UNSUPPORTED_DOCUMENT_TYPE',
  OCR_FAILED: 'OCR_FAILED',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
